ERROR 2022-02-03 09:44:04,147 log 6214 140643216606976 Internal Server Error: /accounts/staff/author/
Traceback (most recent call last):
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'translate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ox23/wsgi-scripts/blog-project/sm_flexdata/views/generic/multi.py", line 180, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/home/ox23/wsgi-scripts/blog-project/sm_flexdata/views/generic/multi.py", line 254, in get_context_data
    self.process_view_settings(context)
  File "/home/ox23/wsgi-scripts/blog-project/sm_flexdata/views/generic/multi.py", line 234, in process_view_settings
    result = self.process_default(context_key, view, initkwargs, args, kwargs)
  File "/home/ox23/wsgi-scripts/blog-project/sm_flexdata/views/generic/multi.py", line 216, in process_default
    response = response.render()
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 183, in render
    template = context.template.engine.select_template(template_name)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/engine.py", line 174, in select_template
    return self.get_template(template_name)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/loaders/cached.py", line 58, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/ox23/wsgi-scripts/test-blog-project/.venv/lib/python3.9/site-packages/django/template/base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 2: 'translate'. Did you forget to register or load this tag?
